In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv('/content/preprocessing_dataset.csv')
df1=df.copy()
df2=df.copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df[['Gender']])
df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

      Name    Age  Gender   Salary Department
0    Alice   25.0       0  50000.0         HR
1      Bob   30.0       1  60000.0    Finance
2  Charlie    NaN       1  55000.0         IT
3    David   40.0       1  58000.0         HR
4      Eve   22.0       0  52000.0         IT
5    Frank   35.0       2  61000.0    Finance
6    Grace  120.0       0      NaN    Finance
7    Henry   28.0       1  59000.0         HR
8      Ivy   29.0       0  63000.0         IT
9     Jack   27.0       1  62000.0    Finance

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder(sparse_output=False)
encoded=one.fit_transform(df1[['Gender']])
df1[['male','Female']]=encoded
df1

      Name    Age  Gender   Salary Department  male  Female
0    Alice   25.0     0.0  50000.0         HR   1.0     0.0
1      Bob   30.0     1.0  60000.0    Finance   0.0     1.0
2  Charlie    NaN     1.0  55000.0         IT   0.0     1.0
3    David   40.0     1.0  58000.0         HR   0.0     1.0
4      Eve   22.0     0.0  52000.0         IT   1.0     0.0
5    Frank   35.0     1.0  61000.0    Finance   0.0     1.0
6    Grace  120.0     0.0      NaN    Finance   1.0     0.0
7    Henry   28.0     1.0  59000.0         HR   0.0     1.0
8      Ivy   29.0     0.0  63000.0         IT   1.0     0.0
9     Jack   27.0     1.0  62000.0    Finance   0.0     1.0

In [ ]:
df2=pd.get_dummies(df,columns=['Department'],drop_first=True)
df2

      Name    Age  Gender   Salary  Department_HR  Department_IT
0    Alice   25.0       0  50000.0           True          False
1      Bob   30.0       1  60000.0          False          False
2  Charlie    NaN       1  55000.0          False           True
3    David   40.0       1  58000.0           True          False
4      Eve   22.0       0  52000.0          False           True
5    Frank   35.0       2  61000.0          False          False
6    Grace  120.0       0      NaN          False          False
7    Henry   28.0       1  59000.0           True          False
8      Ivy   29.0       0  63000.0          False           True
9     Jack   27.0       1  62000.0          False          False